# Non Graded Challenge 5

In [1]:
import numpy as np
import pandas as pd

Nomor 1

In [3]:
T = np.array([
    [[23, 50], [7, 12]],
    [[57, 67], [99, 43]],
    [[75, 21], [57, 12]],
    [[87, 26], [18, 84]],
])

In [4]:
T

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

Nomor 2

In [8]:
A = np.array([[23, 50, 19],
             [7, 12, 109],
             [57, 67, 98]])

B = np.array([[17],
              [22],
              [19]])

In [10]:
#Perkalian A dan B
A.dot(B)

array([[1852],
       [2454],
       [4305]])

Nomor 3

In [11]:
C = np.array([[23, 50, 19],
              [7, 12, 109],
              [ 57, 67, 98]])

In [12]:
C

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [13]:
#Transpose
C.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [15]:
#Determinant
np.linalg.det(C)

131344.0000000002

In [16]:
#Inverse
np.linalg.inv(C)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])